### ISSUE TITLE
[BUG] Pointer Settings and Animations are Broken (V10.285)

### ISSUE THREAD

**Issue by Jacob-Lisner** [Moerill/fvtt-pointer#42]
**Describe the bug**
When editing any feature in Choose Your Pointer! :

- Prior settings fail to save (except selecting a different preset)
- In console there is an Uncaught (in promise) TypeError
- Animations don't seem to work in general (the circular default ping doesn't rotate).

**To Reproduce**
- Open Choose Your Pointer!
- Adjust any setting under "Graphic" or "Animation"

**Module incompatibilities**
- No other modules are activated

**Screenshots/GIFs/Videos**
- Sample Console Error:
pointer.js:44 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'texture')
    at Pointer.draw (pointer.js:44:42)
    at new Pointer (pointer.js:8:8)
    at PointerSettingsMenu._updateObject (settings.js:514:20)
    at PointerSettingsMenu._onSubmit (foundry.js:5833:18)
    at PointerSettingsMenu._onChangeInput (foundry.js:5883:19)
    at HTMLFormElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Desktop (please complete the following information):**
 - Windows
 - Base FoundryVTT application
 - FVTT Version 10.285
 - Module version [e.g. 0.1.0]

**Additional context**
This is a fresh install of Foundry V10.285

**Comment by Rudruk** [comment]
Same here - Foundry v10.286 - no other module activated : Animations don't seem to work in general (the circular default ping doesn't rotate)

**Comment by Cempres** [comment]
Any news on this @Moerill ? We would love an updated v10 version of this module, as it's so much better than the native v10 ones :)

**Comment by santagoy** [comment]
I can corroborate this as well.

**Comment by rmasoni** [comment]
It's still broken :(

**Comment by DavidAremaCarretero** [comment]
PR created to fix this issue: https://github.com/Moerill/fvtt-pointer/pull/47
