### ISSUE TITLE
v9 nauseating bouncy

### ISSUE THREAD

**Issue by jdgcoop** [Moerill/fvtt-pointer#43]
Something in the updates for v10 has broken v9.  Whenever using the "X" and right click to center, the animation never stops and the browser window "bounces" or "strobes" in/out at a perfectly nauseating pace, zooming in/out by a few tics every second.  Using latest version of Chrome and MS Edge, appears to do it on both.  I turned off all the animations in settings, unable to find a setting that changes it.  There were 12 errors in my browser log, here they are in case helpful.  This goes a bit beyond my level of tech skills.

companion-bubble.js:1452 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at companion-bubble.js:1452:20487
    at Generator.next (<anonymous>)
    at An (companion-bubble.js:1452:19905)
DFChatArchive.ts:124 Uncaught (in promise) Error: Could not access the archive folder: worlds/nweh/chat-archive
[Detected 1 package: df-chat-enhance]
    at DFChatArchive.ts:124:12
    at async DFChatArchive.createArchiveFolderIfMissing (DFChatArchive.ts:120:44)
settingsConfig.js:20 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
[Detected 1 package: better-rolltables]
    at Function.values (<anonymous>)
    at Settings.registerSettings (settingsConfig.js:20:35)
    at foundryReady (init.js:47:20)
    at Hooks._call (foundry.js:294:14)
    at Hooks.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5567:11)
    at async Game._initializeGameView (foundry.js:6514:5)
    at async Game.initialize (foundry.js:5431:5)
NW_PurpleEye.png:1          Failed to load resource: the server responded with a status of 404 ()
www-embed-player.js:1524 Uncaught DOMException: Failed to read the 'caches' property from 'Window': Cache storage is disabled because the context is sandboxed and lacks the 'allow-same-origin' flag.
    at https://www.youtube.com/s/player/a336babc/www-embed-player.vflset/www-embed-player.js:1524:11
    at https://www.youtube.com/s/player/a336babc/www-embed-player.vflset/www-embed-player.js:1737:222
hYO0tjJErQ0:7 Uncaught ReferenceError: writeEmbed is not defined
    at hYO0tjJErQ0:7:62552
base.js:491 Uncaught undefined
base.js:491 Uncaught undefined
base.js:491 Uncaught undefined
base.js:491 Uncaught undefined
base.js:491 Uncaught undefined

**Comment by xdy** [comment]
Not Moerill, but I think your best bet is to stick with version 2.3.4 as long as you remain on foundry V9 as 2.4.0 only supports foundry V10.
I.e. uninstall the module to get rid of 2.4.0, then install using this link https://raw.githubusercontent.com/Moerill/fvtt-pointer/32f8630c1d09a7c448bcb299876a8afd735b9dd7/module.json and do not update the module to newer versions.
